### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Jun-T-git** [Jun-T-git/HackU.client#1]
## 完了状態
- フロントエンドメンバー全員が開発環境を構築し，ローカルでページが表示されることを確認する

## 方法
README参照

**Comment by s-taku3** [comment]
mainブランチで起動することを確認しました。
![起動確認](https://user-images.githubusercontent.com/66112754/173610028-c3c98a82-b829-4d88-82cc-4983c23d6781.JPG)
